export default [
  'ageratum',
  'agrostemma (corn cockle)',
  'alyssum',
  'amaranthus',
  "ammi (false queen anne's lace)",
  'ammobium',
  'artemisia (sweet annie)',
  'asclepias (butterfly weed)',
  'aster',
  'atriplex',
  'basil, ornamental',
  'bells of ireland',
  'borage',
  'bupleurum',
  'calendula',
  'campanula',
  'carthamus (safflower)',
  'celosia',
  "centaurea (bachelor's button)",
  'cerinthe',
  'clarkia',
  'columbine',
  'cosmos',
  'craspedia (drumstick flower)',
  'cress, ornamental',
  'cynoglossum',
  'dahlia',
  "daucus (queen anne's lace)",
  'delphinium',
  'dianthus (sweet william)',
  'didiscus',
  'digitalis (foxglove)',
  'dill',
  'dusty miller',
  'echinacea (cornflower)',
  'eryngium'
]
